apiVersion: v1
kind: ConfigMap
metadata:
  name: pg-config
  labels:
    app: postgres
data:
  POSTGRES_PASSWORD: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13.1-alpine
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: pg-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pg-pv
      nodeSelector:
        pg-host: "true"
      volumes:
        - name: pg-pv
